### ISSUE TITLE
Rethink the cache ratio option

### ISSUE THREAD

**Issue by dhendriks** [com-github-javabdd/com.github.javabdd#40]
`JFactory.setCacheRatio` is defined as:

```
    public double setCacheRatio(double x) {
        return bdd_setcacheratio((int)x);
    }
```

The cache ratio is used in `JFactory.bdd_operator_noderesize`:

```
    void bdd_operator_noderesize() {
        if (cacheratio > 0) {
            int newcachesize = bddnodesize / cacheratio;

            BddCache_resize(applycache, newcachesize);
            ...
        }
    }
```

I see two issues:
* The `double x` is converted to an `int`, losing a lot of precision. That is, `1.4` becomes `1`, for instance. In fact, only `1.0`, `2.0`, `3.0` etc are functional. We can't do `1.5` or so.
* The meaning is a bit confusing. I'd have expected a ratio of `0.5` to make the cache half as big as the node array. This is inverted wrt my expectations.
* Currently, any cache ratio in range [0..1) means `0` and thus the cache is not resized.

I propose:
* To keep the `double` a `double`.
* To invert the meaning of the cache ratio.

**Comment by Alberth289346** [comment]
Maybe the floating point value was used to increase the maximum size that you can express. In the pre-64bit era, a double has 56 bit precision while an integer had only 32 bit.
The cast to `int` is very blunt then, maybe it was added afterwards while converting to java ??

In that case, "ratio" in the BDD library would be the size of the cache in number of nodes. It makes sense to avoid floating point operations in the original implementation. Performance is everything in this world. If you want speed you don't want to perform floating point operations if a simple comparison between two numbers can work as well.

**Comment by Alberth289346** [comment]
The `> 0` comparison looks added to avoid crashes only.

**Comment by dhendriks** [comment]
> The `> 0` comparison looks added to avoid crashes only.

It allows to use a fixed cache size, that is initially set and created, and not resized during use.
