### ISSUE TITLE
Allow saturation to provide debug info

### ISSUE THREAD

**Issue by wytseoortwijn** [com-github-javabdd/com.github.javabdd#66]
Currently the saturation operations don't provide any debug information. This makes it difficult for users to e.g. see how some reachability computation progresses.

We should provide some debugging option. Possibly we could add some debug configuration flag that, if set, lets saturation print some things to output. Or, alternatively, lets saturation call some callback function every once in a while.

**Comment by dhendriks** [comment]
I think I would opt for a callback, since that allows more flexibility for the caller to decide the output, in their own format, and to their own target. We may for instance not want to print to stdout, but to an in-memory stream, the Eclipse console, a file, etc, etc.
